// BotWire
// Copyright (C) 2026  Object IT Limited
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

using BotWire.Core.Enums;

namespace BotWire.Core.Models;

/// <summary>A support ticket created when the bot escalates a conversation to a human agent.</summary>
/// <param name="TicketId">Unique identifier for this ticket.</param>
/// <param name="UserMessage">The original user message that triggered escalation.</param>
/// <param name="AiSummary">A short summary of the issue generated by the AI.</param>
/// <param name="Details">Full description of the issue.</param>
/// <param name="SuggestedPriority">Priority level suggested by the AI.</param>
/// <param name="Contact">Optional contact details of the user for follow-up.</param>
/// <param name="History">The full conversation history leading up to escalation.</param>
/// <param name="CreatedAt">UTC timestamp when the ticket was created.</param>
public sealed record SupportTicket(
    string TicketId,
    string UserMessage,
    string AiSummary,
    string Details,
    TicketPriority SuggestedPriority,
    ContactInfo? Contact,
    IReadOnlyList<ChatMessage> History,
    DateTimeOffset CreatedAt);
